/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class common_Encryption */

#ifndef _Included_common_Encryption
#define _Included_common_Encryption
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     common_Encryption
 * Method:    decrypt
 * Signature: ([J[J)V
 */
JNIEXPORT void JNICALL Java_common_Encryption_decrypt
  (JNIEnv *, jobject, jlongArray, jlongArray);

/*
 * Class:     common_Encryption
 * Method:    encrypt
 * Signature: ([J[J)V
 */
JNIEXPORT void JNICALL Java_common_Encryption_encrypt
  (JNIEnv *, jobject, jlongArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
